add_test( catch2_sanity /Users/bruno/Documents/Development/bruno/vulkano_codex/bin/vulkano_tests catch2_sanity  )
set_tests_properties( catch2_sanity PROPERTIES WORKING_DIRECTORY /Users/bruno/Documents/Development/bruno/vulkano_codex/build_release/tests)
add_test( stats_initial_values /Users/bruno/Documents/Development/bruno/vulkano_codex/bin/vulkano_tests stats_initial_values  )
set_tests_properties( stats_initial_values PROPERTIES WORKING_DIRECTORY /Users/bruno/Documents/Development/bruno/vulkano_codex/build_release/tests)
add_test( stats_smoothing_behaviour /Users/bruno/Documents/Development/bruno/vulkano_codex/bin/vulkano_tests stats_smoothing_behaviour  )
set_tests_properties( stats_smoothing_behaviour PROPERTIES WORKING_DIRECTORY /Users/bruno/Documents/Development/bruno/vulkano_codex/build_release/tests)
add_test( [==[Plane generates 4 verts and 6 indices]==] /Users/bruno/Documents/Development/bruno/vulkano_codex/bin/vulkano_tests [==[Plane generates 4 verts and 6 indices]==]  )
set_tests_properties( [==[Plane generates 4 verts and 6 indices]==] PROPERTIES WORKING_DIRECTORY /Users/bruno/Documents/Development/bruno/vulkano_codex/build_release/tests)
add_test( [==[Cube generates 24 verts and 36 indices]==] /Users/bruno/Documents/Development/bruno/vulkano_codex/bin/vulkano_tests [==[Cube generates 24 verts and 36 indices]==]  )
set_tests_properties( [==[Cube generates 24 verts and 36 indices]==] PROPERTIES WORKING_DIRECTORY /Users/bruno/Documents/Development/bruno/vulkano_codex/build_release/tests)
add_test( [==[Icosphere vertex/index counts grow with subdivisions]==] /Users/bruno/Documents/Development/bruno/vulkano_codex/bin/vulkano_tests [==[Icosphere vertex/index counts grow with subdivisions]==]  )
set_tests_properties( [==[Icosphere vertex/index counts grow with subdivisions]==] PROPERTIES WORKING_DIRECTORY /Users/bruno/Documents/Development/bruno/vulkano_codex/build_release/tests)
add_test( [==[Icosphere set_subdivisions rebuilds geometry]==] /Users/bruno/Documents/Development/bruno/vulkano_codex/bin/vulkano_tests [==[Icosphere set_subdivisions rebuilds geometry]==]  )
set_tests_properties( [==[Icosphere set_subdivisions rebuilds geometry]==] PROPERTIES WORKING_DIRECTORY /Users/bruno/Documents/Development/bruno/vulkano_codex/build_release/tests)
add_test( [==[Plane UV tiling setter updates UVs]==] /Users/bruno/Documents/Development/bruno/vulkano_codex/bin/vulkano_tests [==[Plane UV tiling setter updates UVs]==]  )
set_tests_properties( [==[Plane UV tiling setter updates UVs]==] PROPERTIES WORKING_DIRECTORY /Users/bruno/Documents/Development/bruno/vulkano_codex/build_release/tests)
add_test( [==[Checkerboard image dimensions and pattern]==] /Users/bruno/Documents/Development/bruno/vulkano_codex/bin/vulkano_tests [==[Checkerboard image dimensions and pattern]==]  )
set_tests_properties( [==[Checkerboard image dimensions and pattern]==] PROPERTIES WORKING_DIRECTORY /Users/bruno/Documents/Development/bruno/vulkano_codex/build_release/tests)
add_test( [==[Blue-noise-ish normal map basics]==] /Users/bruno/Documents/Development/bruno/vulkano_codex/bin/vulkano_tests [==[Blue-noise-ish normal map basics]==]  )
set_tests_properties( [==[Blue-noise-ish normal map basics]==] PROPERTIES WORKING_DIRECTORY /Users/bruno/Documents/Development/bruno/vulkano_codex/build_release/tests)
add_test( camera_look_delta_keeps_eye_position /Users/bruno/Documents/Development/bruno/vulkano_codex/bin/vulkano_tests camera_look_delta_keeps_eye_position  )
set_tests_properties( camera_look_delta_keeps_eye_position PROPERTIES WORKING_DIRECTORY /Users/bruno/Documents/Development/bruno/vulkano_codex/build_release/tests)
add_test( camera_move_local_changes_position /Users/bruno/Documents/Development/bruno/vulkano_codex/bin/vulkano_tests camera_move_local_changes_position  )
set_tests_properties( camera_move_local_changes_position PROPERTIES WORKING_DIRECTORY /Users/bruno/Documents/Development/bruno/vulkano_codex/build_release/tests)
add_test( camera_forward_and_right_are_orthogonal /Users/bruno/Documents/Development/bruno/vulkano_codex/bin/vulkano_tests camera_forward_and_right_are_orthogonal  )
set_tests_properties( camera_forward_and_right_are_orthogonal PROPERTIES WORKING_DIRECTORY /Users/bruno/Documents/Development/bruno/vulkano_codex/build_release/tests)
set( vulkano_tests_TESTS catch2_sanity stats_initial_values stats_smoothing_behaviour [==[Plane generates 4 verts and 6 indices]==] [==[Cube generates 24 verts and 36 indices]==] [==[Icosphere vertex/index counts grow with subdivisions]==] [==[Icosphere set_subdivisions rebuilds geometry]==] [==[Plane UV tiling setter updates UVs]==] [==[Checkerboard image dimensions and pattern]==] [==[Blue-noise-ish normal map basics]==] camera_look_delta_keeps_eye_position camera_move_local_changes_position camera_forward_and_right_are_orthogonal)
